Repository quotientbot/Quotient-Bot, pull requests merged in 2023-06, with the labels that each got.

#128 Solving my first Issue
  src/server/app/payment.py
  src/server/templates/response.html
Labels: question

#134 add slotsinfo command to scrims group
  src/cogs/esports/slash/scrims.py
Labels: new-feature

#138 setup a basic global ratelimit mechanism
  src/core/Bot.py
  src/core/cooldown.py
Labels: enhancement

#141 Feature/tourney fake tags feature
  src/cogs/esports/errors.py
  src/cogs/esports/helpers/tourney.py
  src/cogs/esports/views/tourney/_buttons.py
  src/cogs/esports/views/tourney/_editor.py
  src/constants.py
  src/models/esports/tourney.py
Labels: enhancement
